### ISSUE TITLE
Attribute Error on debug_log_format

### ISSUE THREAD

**Issue by stokkie90** [dmsimard/ara#77] opened 2016-05-30 09:15 UTC
In the latest (0.7.0) version I get this error when using the app

```
Traceback (most recent call last):
  File "/usr/bin/ara-manage", line 6, in <module>
    from ara.manage import main
  File "/usr/lib/python2.7/site-packages/ara/__init__.py", line 26, in <module>
    app = create_app()
  File "/usr/lib/python2.7/site-packages/ara/webapp.py", line 49, in create_app
    configure_logging(app)
  File "/usr/lib/python2.7/site-packages/ara/webapp.py", line 94, in configure_logging
    'ARA_LOG_FORMAT', app.debug_log_format)))
AttributeError: 'Flask' object has no attribute 'debug_log_format'

```

**Comment by hguemar** [comment] 2016-05-30 11:41
Same failure in RDO CI.
https://ci.centos.org/view/rdo/view/weirdo/job/weirdo-generic-packstack-scenario002/47/console

**Comment by apevec** [comment] 2016-05-30 11:57
Suspect: https://pypi.python.org/pypi/Flask/0.11#downloads released on May 29th

**Comment by apevec** [comment] 2016-05-30 12:00
Yep, https://github.com/pallets/flask/blob/21d595bee73e65a28201709bd1a8b97c42aff5d2/docs/upgrading.rst#debugging

**Comment by dmsimard** [comment] 2016-05-30 12:23
Thanks. 0.7.1 is out on github and pypi with flask pinned to 0.10 while we properly test 0.11. Keeping this opened until this issue is fixed with 0.11.

**Comment by dmsimard** [comment] 2016-05-30 14:03
This error is easy to reproduce with the existing tests with flask 0.11.

This patch looks like it fixes it but I'm wondering if we should just offload all the logging through Flask. @larsks, thoughts ?

    diff --git a/ara/webapp.py b/ara/webapp.py
    index 86be3dc..0a55958 100644
    --- a/ara/webapp.py
    +++ b/ara/webapp.py
    @@ -16,6 +16,7 @@ import os
    import logging
    
    from flask import Flask
    +from flask import logging as flask_logging
    
    from ara.models import db
    from ara.filters import configure_template_filters
    @@ -91,7 +92,7 @@ def configure_logging(app):
            handler = logging.FileHandler(app.config['ARA_LOG_FILE'])
            handler.setFormatter(
                logging.Formatter(app.config.get(
    -                'ARA_LOG_FORMAT', app.debug_log_format)))
    +                'ARA_LOG_FORMAT', flask_logging.DEBUG_LOG_FORMAT)))
            logger = logging.getLogger(app.logger_name)
            logger.setLevel(app.config['ARA_LOG_LEVEL'])
            del logger.handlers[:]
    diff --git a/requirements.txt b/requirements.txt
    index 7de3164..8200df6 100644
    --- a/requirements.txt
    +++ b/requirements.txt
    @@ -1,4 +1,4 @@
    -Flask==0.10
    +Flask==0.11
    Flask-SQLAlchemy
    Flask-Script
    Frozen-Flask

**Comment by larsks** [comment] 2016-05-31 01:09
I am not attached to this particular solution as long as it remains easy to direct logs to a particular file with a particular level setting.  So if you can get flask to take care of everything for us, I am :+1: on that idea; I just hadn't investigated much.

**Closed** 2016-05-31 15:26 UTC
